### PR TITLE
Update extension SDK versions.

### PR DESCRIPTION
**Pull request by bryans99**
Also update lodash, dependabot reports a minor issue.

### CODE REVIEW

**Review by jkaster — DISMISSED** [review]
LGTM

**Comment by whscullin** [comment]
I feel like somehow your linter has gone haywire.

**Comment by whscullin** [comment]
These warnings seem significant:
```
WARNING in ./src/index.tsx 70:25-43
"export 'ComponentsProvider' was not found in '@looker/components'

WARNING in ./src/demo/Extension.tsx 134:89-99
"export 'MessageBar' was not found in '@looker/components'
 @ ./src/index.tsx
```

**Comment by bryans99** [comment]
> These warnings seem significant:
> 
> ```
> WARNING in ./src/index.tsx 70:25-43
> "export 'ComponentsProvider' was not found in '@looker/components'
> 
> WARNING in ./src/demo/Extension.tsx 134:89-99
> "export 'MessageBar' was not found in '@looker/components'
>  @ ./src/index.tsx
> ```

How did you get those? I'm not seeing it in my local and I'm not seeing them in the github build. The error is saying you don't have the latest (or near latest) @looker/components. should be "@looker/components": "0.9.6",

**Comment by bryans99** [comment]
> I feel like somehow your linter has gone haywire.

Oh shoot! You right. Let me fix that one!

**Review by whscullin — APPROVED** [review]
Whoops, swear I ran yarn but I guess not. Carry on.

**Pull request merged**
