### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by bryans99**
Fix versions
Remove yarn lock so latest versions of dependencies are picked up

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Why not re-run `yarn` to re-generate the `yarn.lock`?

**Comment by bryans99** [comment]
> Why not re-run `yarn` to re-generate the `yarn.lock`?

It's a good question and warrants further discussion because perhaps I am not thinking this through.

Some history. When the initial template was created, it was decided to be agnostic to builder (yarn or npm). We used yarn but decided NOT to commit yarn.lock.

When I created the two new templates I forgot about the yarn lock and committed them.

I got burnt recently, because the core SDK was updated and broke extensions (twice!). The first one we got away with for a month (at least with the kitchen sink and redux templates) because the yarn.lock saved us. The issues were found because someone deleted their node modules directory and yarn lock files, did an install and everything went to pieces. I had not noticed because of the yarn lock file.

My thinking is that if there is no package lock or yarn lock I'm gonna be notified of issues sooner because someone is going to clone the repo's and get the latest versions. As I reflect, I'm thinking this is flawed thinking but based upon the initial notion of being builder agnostic.

Thoughts?

I'm not opposed to committing the yarn lock files and updating the docs to recommend using yarn. I'm also in the process of changing the repos to force a review and do a build on push.

**Comment by bryans99** [comment]
Added yarn lock back in. Added git action to ensure clean build. Enforce review

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
